### ISSUE TITLE
Dashku and express

### ISSUE THREAD

**Issue by afrozl** [dashku/dashku#64]
Is it possible to integrate Dashku with an existing Express application? I would like to be able to use Dashku to handle dashboarding duties within an Express app (Keystonejs).

I've followed the directions that I've found in various threads around socketstream and Express, however I am unclear on how the routing is split between Express and socketstream. 

I also appear to be unable to connect to engine.io as I see errors in the logs:

GET http://127.0.0.1:3000/engine.io/?EIO=3&transport=polling&t=1435070482416-6 404 (Not Found)

**Comment by paulbjensen** [comment]
Hi @afrozl, it should be possible given that the API is loaded via connect middleware. Is there a place for the code where this error is occurring?

**Comment by afrozl** [comment]
so the goal is that Dashku would run under the /dashboards path and everything else would be handled by keystone.  I've added a route for that in express:

<pre>
    app.get('/dashboards/', function (req, res) {
        res.serve('main')}
    )
</pre>

socketstream is getting started in the main app.js, however when I access the /dashboards path, I can not access any of the static assets or engine.io. All return 404 errors.

**Comment by afrozl** [comment]
it appears to be a routing issue as the requests are not getting resolved to the correct path

<pre>GET /assets/main/4yr1x2Hw.js?mod=eventemitter2 404 1259.924 ms</pre>

I've set the static assets path for the Express app to also use /client, however that hasn't helped. Any suggestions on where to look next?

to eliminate the possibility of a engine.io/websockets issue, I did integrate the app with primus and was able to get bi-directional communications working over websockets,

**Comment by paulbjensen** [comment]
SocketStream using runs with it's own web server, and you mount the express app in it, not the other way around. There is an example of how to do this somewhere, which I will dig out.

**Comment by paulbjensen** [comment]
Hi, 

This version of Dashku is going to be unsupported, as there is a new, much better version coming out in the future. Will close this issue.
