### ISSUE TITLE
Unable to build bcrypt on windows

### ISSUE THREAD

**Issue by xlenz** [dashku/dashku#71]
there are tons of issues with bcrypt. Lets use bcryptjs instead.
https://npmjs.org/package/bcryptjs

Similar issues: http://stackoverflow.com/questions/19822643/what-is-an-alternative-for-bcrypt-to-use-with-node

**Comment by paulbjensen** [comment]
Hi, 

This version of Dashku is going to be unsupported, as there is a new, much better version coming out in the future. Will close this issue.
